class_name Directories

static var directories : Dictionary = {"C" : ["Dell", "Intel", "logs", "Program Files", "Program Files (x86)", "Users", "Windows"],
	"Dell" : [],
	"Intel" : [],
	"logs" : [],
	"Program Files" : [],
	"Program Files (x86)" : [],
	"Users" : ["Inteli", "@TempUser"],
	"Windows" : ["addins", "en-US", "Network", "pt-BR", "System", "System32", "Temp"],
	"Inteli" : ["AppData", "Contacts", "Desktop", "Documents", "Downloads", "Favourite", "Music", "Pictures", "Videos"],
	"@TempUser" : [],
	"addins" : [],
	"en-US" : [],
	"Network" : [],
	"pt-BR" : [],
	"System" : [],
	"System32" : [],
	"Temp" : [],
	"AppData" : [],
	"Contacts" : [],
	"Desktop" : [],
	"Documents" : [],
	"Downloads" : [],
	"Favourite" : [],
	"Music" : [],
	"Pictures" : [],
	"Videos" : []}
