class_name Directories

static var directories : Dictionary = {"C" : ["Dell", "Intel", "logs", "ProgramFiles", "ProgramFiles(x86)", "Users", "Windows"],
	"Dell" : [],
	"Intel" : [],
	"logs" : [],
	"ProgramFiles" : ["Git", "MyGames", "WinRAR", "default.txt", "c23e5so67hc9e.exe"],
	"ProgramFiles(x86)" : ["Common", "WindowsXPInstallationAssistant", "temp.phpp"],
	"Users" : ["Inteli", "@TempUser"],
	"Windows" : ["addins", "en-US", "Network", "pt-BR", "System", "System32", "Temp"],
	"Inteli" : ["AppData", "Desktop", "Documents", "Downloads", "Favourite", "Music", "Pictures", "Videos"],
	"@TempUser" : [],
	"Git" : ["git_bash.exe", "git_cmd.exe", "LICENSE.txt"],
	"WinRAR" : ["WinRAR.exe"],
	"MyGames" : ["LoL"],
	"Common" : [],
	"WindowsXPInstallationAssistant" : [],
	"addins" : [],
	"en-US" : [],
	"Network" : [],
	"pt-BR" : [],
	"System" : [],
	"System32" : ["AdvancedInstallers", "Boot", "CatRoot", "config", "drivers", "policy", "cmd.exe", "system.dll", "sys.shell"],
	"Temp" : [],
	"AppData" : ["lol_logs.txt"],
	"Desktop" : ["LoL.exe", "cmd.exe", "Trashcan.exe"],
	"Documents" : ["linkedin_pfp.jpg", "participation_certificate.pdf", "passport.pdf"],
	"Downloads" : ["git_installer.exe", "lol_installer.exe", "the_sims_free_complete_2001.exe"],
	"Favourite" : [],
	"Music" : ["how_you_remind_me_nickelback.mp3", "whenever_wherever_shakira.mp3"],
	"Pictures" : ["gamelab_logo.png", "inteli_logo.png"],
	"Videos" : ["onboarding_2001.mp4"],
	"LoL" : ["Clips", "LoL.exe"],
	"AdvancedInstallers" : [],
	"app" : [],
	"Boot" : [],
	"CatRoot" : [],
	"config" : [],
	"drivers" : [],
	"policy" : [],
	"Clips" : ["insane_thresh_hook.mp4"]}
